function EpiosStep2006labelsS2 = excel2table_label_BP(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  EPIOSSTEP2006LABELSS2 = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  EPIOSSTEP2006LABELSS2 = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  EPIOSSTEP2006LABELSS2 = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  EpiosStep2006labelsS2 = importfile("X:\4 e-Lab\EvM\Projects\EPIOS\Patients\Epios_Step2_006\labels\Epios_Step2_006_labels.xlsx", "Channels_BP", [2, 188]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Mar-2023 08:49:19

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 188];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":F" + dataLines(1, 2);

% % Specify column names and types
% opts.VariableNames = ["label_BP", "Var2", "Var3", "labelP", "labelN", "type"];
% opts.SelectedVariableNames = ["label_BP", "labelP", "labelN", "type"];
% opts.VariableTypes = ["string", "char", "char", "string", "string", "categorical"];
% 
% % Specify variable properties
% opts = setvaropts(opts, ["label_BP", "Var2", "Var3", "labelP", "labelN"], "WhitespaceRule", "preserve");
% opts = setvaropts(opts, ["label_BP", "Var2", "Var3", "labelP", "labelN", "type"], "EmptyFieldRule", "auto");

% Import the data
% EpiosStep2006labelsS2 = readtable(workbookFile, opts, "UseExcel", false);
EpiosStep2006labelsS2 = readtable(workbookFile,'Sheet',sheetName);
% EpiosStep2006labelsS2 = EpiosStep2006labelsS2(~isnan(EpiosStep2006labelsS2.type),:);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":F" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    EpiosStep2006labelsS2 = [EpiosStep2006labelsS2; tb]; %#ok<AGROW>
end

end