function logfile = import_logfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EL006LOGBMCLI = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  logfile = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  EL006logBMcli = importfile("/Users/ellenvanmaren/Dropbox (ARTORG)/PhD_EvM/20210505_EL006_log_BM_cli.log", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 30-Jun-2021 11:15:01

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [",", ":"];

% Specify column names and types
opts.VariableNames = ["date", "hour", "min", "s", "us", "type", "Num", "ChanP", "ChanN", "ISI_s", "Int_p", "Int_c", "IPI_ms", "block", "currentflow"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "type", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["ISI_s", "Int_p", "Int_c", "IPI_ms", "block", "currentflow"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["ISI_s", "Int_p", "Int_c", "IPI_ms", "block", "currentflow"], "ThousandsSeparator", ",");

% Import the data
logfile = readtable(filename, opts);

end