function BP_label = importfile_BPlabels(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  EL016LOOKUPS3 = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  EL016LOOKUPS3 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  EL016LOOKUPS3 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  EL016lookupS3 = importfile("T:\EL_experiment\Patients\EL016\infos\EL016_lookup.xlsx", "Channels_BP", [2, 92]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Sep-2022 17:49:10

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 92];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":H" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["label_BP", "chan_BP_P", "chan_BP_N", "labelP", "labelN", "type", "labelP_EDF", "labelN_EDF"];
opts.VariableTypes = ["string", "double", "double", "categorical", "categorical", "categorical", "categorical", "categorical"];

% Specify variable properties
opts = setvaropts(opts, "label_BP", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["label_BP", "labelP", "labelN", "type", "labelP_EDF", "labelN_EDF"], "EmptyFieldRule", "auto");

% Import the data
BP_label = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":H" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    BP_label = [BP_label; tb]; %#ok<AGROW>
end

end