function labels = import_BP_new(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  EL022LABELSS3 = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  EL022LABELSS3 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  EL022LABELSS3 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  EL022labelsS3 = importfile("X:\4 e-Lab\Patients\EL022\Electrodes\EL022_labels.xlsx", "BP", [2, 119]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Mar-2023 15:31:45

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 119];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 16);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":P" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["label", "Area", "Clinic", "Num", "ChanP", "ChanN", "x", "y", "z", "ChanP_SM", "ChanN_SM", "Region", "Hemisphere", "labelP_EDF", "labelN_EDF", "type"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "categorical"];

% Specify variable properties
opts = setvaropts(opts, ["label", "Area", "Clinic", "Region", "Hemisphere", "labelP_EDF", "labelN_EDF"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["label", "Area", "Clinic", "Region", "Hemisphere", "labelP_EDF", "labelN_EDF", "type"], "EmptyFieldRule", "auto");

% Import the data
labels = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":P" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    labels = [labels; tb]; %#ok<AGROW>
end

end