function log = importfile_log_2(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EL02220230313LOG = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  EL02220230313LOG = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  EL02220230313log = importfile("X:\4 e-Lab\Patients\EL022\Data_Raw\EL_experiment\EL022_20230313_log.log", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Mar-2023 09:17:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [" ", ",", ":"];

% Specify column names and types
opts.VariableNames = ["date", "hour", "min", "s", "us", "type", "run", "block", "StimNum", "ChanP", "ChanN", "ISI_s", "Int_prob", "Int_cond", "IPI_ms", "currentflow"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["date", "type", "run"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["hour", "ISI_s", "Int_p", "Int_c", "IPI_ms", "currentflow"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["hour", "ISI_s", "Int_p", "Int_c", "IPI_ms", "currentflow"], "ThousandsSeparator", ",");

% Import the data
log = readtable(filename, opts);

end